### ISSUE TITLE
Baselines path incorrect in Wiki documentation

### ISSUE THREAD

**Issue by goneafk** [usnistgov/macos_security#1]
### Summary

On the Scripts page of the Wiki, each example uses the path baseline.
`python3 create_guide.py ../baseline/moderate.yaml -o ../build/MyBaselineGuide.adoc`

However, the currently committed code has the folder named `baselines` not `baseline`.

### Example lines

`python3 create_guide.py ../baseline/moderate.yaml -o ../build/MyBaselineGuide.adoc`
`python3 script_generator.py ../baseline/moderate.yaml`
`python3 profile_generator.py ../baseline/moderate.yaml`

**Comment by robertgendler** [comment]
Fixed.
