### ISSUE TITLE
Add sections for project and local site authors to custom baselines

### ISSUE THREAD

**Issue by escobarj** [usnistgov/macos_security#105]
Currently when creating a custom baseline the authors section of the baseline yaml is just a stub. It's designed to be filled in by the user.
Instead, I propose creating two sections. One pre-populated with the mSCP authors, and one to be filled in by the creators of the custom baseline.

Here is an example of how the generated baseline yaml could look.

```
authors: |
  .macOS Security Compliance Project
  |===
  |Dan Brodjieski|National Aeronautics and Space Administration
  |Allen Golbig|Jamf
  |Bob Gendler|National Institute of Standards and Technology
  |===

  .YourOrg
  |===
  |Name|YourOrg - Team1
  |Name2|YourOrg - Team2
  |===
```

The YourOrg section can then be filled in with the appropriate information by the custom baseline creators.

**Comment by golbiga** [comment]
@escobarj take a look at `dev_mont_authors`. Let us know what you think.

**Comment by brodjieski** [comment]
branch name changed to `dev_mont_issue105`...
