### ISSUE TITLE
Setting for TimeServer

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#11]
### Summary

https://developer.apple.com/documentation/devicemanagement/timeserver
The domain com.apple.MCX with they key timeServer can be overruled by the systemsetup binary

### Steps to reproduce

sudo systemsetup -setnetworktimeserver "example.com"

### Operating System version

macOS 10.15.5
### What is the expected *correct* behavior?

The expected behavior is that a configuration sets the setting permanently.

### Possible fixes

Setting the time server using
systemsetup -setnetworktimeserver "time-a.nist.gov,time-b.nist.gov"

Checking the time server using
systemsetup -getnetworktimeserver

**Comment by golbiga** [comment]
Configuration profile will re-apply settings, keeping as is.
