### ISSUE TITLE
mismatched test and mobileconfig for Monterey os_burn_support_disable

### ISSUE THREAD

**Issue by bernstei** [usnistgov/macos_security#132]
https://github.com/usnistgov/macos_security/blob/1b03ed4b0d0760e7e1e66893df293859d54fa23f/rules/os/os_burn_support_disable.yaml#L11

I think that the `ProhibitBurn` test should look for the value 1, not 0, and (on my machine at least) the BurnSupport returns `off`, not `"off"`, so the test fails to recognize it.

**Comment by marcindulak** [comment]
The issue is still present in the latest main https://github.com/usnistgov/macos_security/commit/06cc0d2614da5b6f478b6f1ff45b059bb7c6aa5a.
When the fixes will be merged?

```
sw_vers
# Output:
# ProductName:      macOS
# ProductVersion:   12.5.1
# BuildVersion:     21G83
```

```
# os_burn_support_disable failed (Result: 0, Expected: {integer: 2})
sudo /usr/bin/profiles -P -o stdout | /usr/bin/grep -E 'ProhibitBurn|BurnSupport'
# Output:
#                         ProhibitBurn = 1;
#                        BurnSupport = off;
```

**Comment by robertgendler** [comment]
These are on the OS branches, if you do a pull from there that and many other things are fixed and updated. Our next release and merge into main will be when Ventura is released.
