### ISSUE TITLE
audit_retention_configure_sixty_days remediation not getting picked up by Jamf Protect insights

### ISSUE THREAD

**Issue by ZaoDigital** [usnistgov/macos_security#145]
```
fix: |
  [source,bash]
  ----
  /usr/bin/sed -i.bak 's/^expire-after.*/expire-after:60d or 1G/' /etc/security/audit_control; /usr/sbin/audit -s
```
Running Monterey 12.4:
The lowercase 'or' between 60d and 1G is causing Jamf Protect to not have compliance with the associated insight

Uppercasing the 'OR' will remediate it as expected

(I would submit a PR for the fix but the contribution guidelines suggest I should open in issues instead, yeah?)

**Comment by robertgendler** [comment]
Looks like from the man page it should be in capitals. So AND or OR. We'll update and fix things.
