### ISSUE TITLE
Filename tweak

### ISSUE THREAD

**Issue by macnotes** [usnistgov/macos_security#15]
In [the docs](https://github.com/usnistgov/macos_security/wiki/Scripts#baseline_identifypy), baseline_identify.py has _ (underscore) as the word separator in the file name shown in the topic heading and example usage. This is consistent with the convention used in the file names of the other ./scripts files. In the repo, a "-" (dash) is used. 

Suggestion: Leave the wiki doc as-is and change the filename from baseline-identify.py to baseline_identify.py

**Comment by golbiga** [comment]
This will be fixed in an upcoming release. Thanks!

**Comment by robertgendler** [comment]
The script has been removed in our current release. So this has been resolved.
