### ISSUE TITLE
Ummm, HOWTO

### ISSUE THREAD

**Issue by Honestpuck** [usnistgov/macos_security#162]
I've got a bunch of small fixes such as spelling errors.

These would seem to be useful across all branches. Should I put them in `main` and they are then propagated through the OS branches by some magical method I understand not?

**Comment by golbiga** [comment]
Please do all PRs against one of the OS branches and then we can propagate it down. I'd probably recommend doing it against `dev_ventura`. We only touch main during releases, which will be around the time of Ventura's public release.

**Comment by Honestpuck** [comment]
Thanks. Will do.

**Comment by marcindulak** [comment]
Could you please link the PR here so issue subscribers are notified about the progress?
