### ISSUE TITLE
Format problem in remediation of a number of 'os' section rules

### ISSUE THREAD

**Issue by Honestpuck** [usnistgov/macos_security#164]
### Summary

There are a number of rules in the `os` section that set a key in the `mount-controls` key in `com.apple.systemuiserver` While the mobileconfigs are generated properly there must be a minor format problem because in the guidance the remediation description just has the `mount-controls` key but not the sub key and settings array.

### Steps to reproduce

Generate the `all_rules` guidance and go to section 9, you can see the error.

### Operating System version

macOS 12.5.1 the `dev_ventura` branch.

### What is the current *bug* behavior?

The remediation is just `<key>mount-controls</key>`

### What is the expected *correct* behavior?

In the remediation it should have:

```
<key>mount-controls</key>
	<dict>
		<key>blankbd</key>
		<array>
			<string>alert</string>
			<string>eject</string>
		</array>
<dict>
```

### Possible fixes

I tried to correct the format myself but couldn't manage it. If somebody can fix one I will copy it across the lot.

**Comment by golbiga** [comment]
This is fixed and merged into the os branches. It will get merged into main during the ventura release
