### ISSUE TITLE
profile_generator.py doesn't work unless you change directory to the "scripts" directory first

### ISSUE THREAD

**Issue by pudquick** [usnistgov/macos_security#18]
### Summary

If you attempt to run profile_generator.py from any directory other than scripts, it doesn't work.

### Steps to reproduce

- Check out project
- Install requirements
- From the base of the project run: `./scripts/profile_generator.py baselines/800-53_low.yaml`

### What is the current *bug* behavior?

Script looks like it's running (warning prints), but no mobileconfigs are generated.

### What is the expected *correct* behavior?

mobileconfigs are generated in build folder.

**Comment by robertgendler** [comment]
Resolved. You can now run the generate_guidance script from any directory.
