### ISSUE TITLE
Big Sur Compliance Script Error

### ISSUE THREAD

**Issue by paparooky** [usnistgov/macos_security#189]
### Summary
generated compliance script for Big Sur cis_lvl1 or lvl2 doesn't run
 
### Steps to reproduce
Verify current git repo
checkout to Big Sur branch
% ./scripts/generate_baseline.py -k cis_lvl1 [or lvl2]
% ./scripts/generate_guidance.py -s -p build/baselines/cis_lvl1 [or 2].yaml
Errors:
Generating configuration profiles...
There are errors in the following files, please correct the .yaml file(s)!
../rules/os/os_terminal_secure_keyboard_enable.yaml
../rules/os/os_terminal_secure_keyboard_enable.yaml
../rules/sysprefs/sysprefs_bluetooth_menu_enable.yaml
../rules/sysprefs/sysprefs_bluetooth_menu_enable.yaml
../rules/sysprefs/sysprefs_wifi_menu_enable.yaml
../rules/sysprefs/sysprefs_wifi_menu_enable.yaml
% sudo ./build/cis_lvl1/cis_lvl1_compliance.sh
Returns:
./build/cis_lvl1/cis_lvl1_compliance.sh:3850: condition expected: $result_value

### Operating System version
11.7

### Intel or Apple Silicon
VMware VM hosted on Intel Mac
Not seeing this behavior on Catalina or Monterey VMs in the respective branches

### What is the current *bug* behavior?
See steps to produce

### What is the expected *correct* behavior?
No errors in rule .yaml files
Compliance script runs
I have 

### Relevant logs and/or screenshots
none

### Output of checks
See steps to produce

### Possible fixes

**Comment by golbiga** [comment]
@paparooky Looks like we had an issue with the yaml in `sysprefs_time_server_configure`. I've fixed it and tested both cis lvl1 and 2. Please checkout `dev_big_sur_issue189` and test it out and see if that resolves your issue. Thanks for reporting the issue.

**Comment by paparooky** [comment]
@golbiga That does the trick. Thanks!

**Comment by golbiga** [comment]
We updated the big_sur branch. Closing the issue.
