### ISSUE TITLE
JCE CIS Level 1 Rules are showing 2.9.3 (Level 2)

### ISSUE THREAD

**Issue by gsprague** [usnistgov/macos_security#198]
### Summary

(Summarize the bug encountered concisely)
When using the Jamf Compliance Editor and selecting the CIS Level 1 Ventura benchmark, it shows 2.9.3 which is CIS Level 2. 

### Steps to reproduce

(How one can reproduce the issue - this is very important)
1. Open JCE
2. Select "Create new project"
3. Choose "ventura" branch and click "Create"
4. Save the project somewhere and click "Save"
5. Choose Security Benchmark "CIS Benchmark - Level 1"  and click "OK"
6. You will now see 2 Level 2 rules for 2.9.3 listed with the Level 1 rule set. Screenshot attached...

### Operating System version

(macOS Version and build)
macOS v13 (22A380)

### Intel or Apple Silicon

(Intel based process or Apple Silicon Mac)
Intel

### What is the current *bug* behavior?

(What actually happens)
2 rules for CIS Level 2 #2.9.3 are showing in the CIS Level 1 rule set. 

### What is the expected *correct* behavior?

(What you should see instead)
2 rules for CIS Level 2 #2.9.3 should not be showing in the CIS Level 1 rule set.

### Relevant logs and/or screenshots
<img width="724" alt="Screen Shot 2022-11-03 at 8 58 07 AM" src="https://user-images.githubusercontent.com/810706/199727526-2ca438da-515c-4b6b-bd97-0c3a3da5211d.png">

(Paste any relevant logs - please use code blocks (```) to format console output, logs, and code as it's tough to read otherwise.)

### Output of checks

(Paste any output that occurs with the bug)

### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)
Take the following CIS Level 2 rules out of the CIS Level 1 baseline yaml file
Project File Path:
../baselines/cis_lvl1.yaml
Rules to Remove from the '- section: "macos"':
      - os_hibernate_mode_destroyfvkeyonstandby_enable
      - os_hibernate_mode_enable

**Comment by gsprague** [comment]
@golbiga These will also need to be updated in the Big Sur and Monterey branches. They are showing up in JCE as rule #2.8.3.

**Comment by golbiga** [comment]
Updated in monterey and Big Sur. Closing this issue. Thanks.
