### ISSUE TITLE
os_hibernate_mode_enable Missing hibernatemode (and spelling error)

### ISSUE THREAD

**Issue by jmahlman** [usnistgov/macos_security#203]
### Summary

The rule `os_hibernate_mode_enable` is missing the actual setting for `hibernatemode`. There is also a spelling error in the discussion.

### Operating System version

Big Sur, Monterey, ventura

### Intel or Apple Silicon

Both

### What is the current *bug* behavior?

The rule does not set the `hibernatemode` to 25 as outlined in the CIS Benchmark.
The spelling error in the discussion: "instate" should be instant"

### What is the expected *correct* behavior?

For all Macs, `hibernatemode` should be set to 25. 

### Relevant logs and/or screenshots

https://workbench.cisecurity.org/sections/1447545/recommendations/2326248

### Possible fixes

Spelling error:
- Update line 6 of the check to `  NOTE: Hibernate mode will disable instant wake on Apple Silicon laptops.`

Hibernate mode:
- After lines 40 and 42, add the following command: `/usr/bin/pmset -a hibernatemode 25`

**Comment by golbiga** [comment]
merged into ventura and will be checked out into others.
