### ISSUE TITLE
How to run macOS security compliance script on multiple mac devices using workspaceone MDM

### ISSUE THREAD

**Issue by nileshgaikwadflex** [usnistgov/macos_security#205]
### Problem to solve

With the help of the https://github.com/usnistgov/macos_security/wiki i am able to build the "800-53r5_moderate_compliance.sh" script however i can not push it using our VMware workspace one MDM
With VMware workspace one we dont have option to run the interactive script with --check parameter. 
Let me know the way to push the compliance check script using Vmware MDM.

**Comment by robertgendler** [comment]
Just came across this link this week. Hopefully it'll help.

https://github.com/vmware-samples/euc-samples/tree/master/UEM-Samples/Utilities%20and%20Tools/macOS/Baselines

**Comment by robertgendler** [comment]
@nileshgaikwadflex https://techzone.vmware.com/resource/enforcing-macos-security-compliance-project-baselines-workspace-one-operational-tutorial#configure-compliance-sensors-in-workspace-one-uem
