### ISSUE TITLE
os_sshd_permit_root_login_configure remediation code appends "permitrootlogin no"

### ISSUE THREAD

**Issue by cipineda** [usnistgov/macos_security#206]
### Summary

The file created by the remediation code is appending the text "permitrootlogin no", each time the script is executed.

My file /etc/ssh/sshd_config.d/01-mscp-sshd.conf has 369 lines with the same text, I guess this is looping because of a previous issue (#194) I have open with you guys.

### Steps to reproduce

This code, simply appends the text "permitrootlogin no", it does not check if the file is there and if the text already exists, it simply appends to it.

`include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')
if [[ -z $include_dir ]]; then
/usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/"
    /etc/ssh/sshd_config
fi
echo "permitrootlogin no" >> "${include_dir}01-mscp-sshd.conf"
for file in $(ls ${include_dir}); do
if [[ "$file" == "100-macos.conf" ]]; then
continue fi
if [[ "$file" == "01-mscp-sshd.conf" ]]; then break`

### Operating System version

ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C5050e

ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400

### Intel or Apple Silicon

Intel based process and Apple Silicon Mac

### What is the current *bug* behavior?

the file /etc/ssh/sshd_config.d/01-mscp-sshd.conf has 369 with the same text   "permitrootlogin no"

### What is the expected *correct* behavior?

The remediation script should validate if the text already exists, and then simply exit

### Output of checks

`cat /etc/ssh/sshd_config.d/01-mscp-sshd.conf | wc -l`
     369

`cat 01-mscp-sshd.conf `
permitrootlogin no
permitrootlogin no
permitrootlogin no
permitrootlogin no
permitrootlogin no
permitrootlogin no

### Possible fixes

check if the text   "permitrootlogin no" exists on the file, if yes, then do not add to the conf file

`result_value=$(cat ${include_dir}01-mscp-sshd.conf | grep "permitrootlogin no" | wc -l | xargs)
if [[ $result_value -eq 0 ]]; then
  echo "permitrootlogin no" >> "${include_dir}01-mscp-sshd.conf"
fi`

**Comment by golbiga** [comment]
We're going to look into updating the ssh fix to prevent duplicates.

**Comment by robertgendler** [comment]
this fix was merged into main. closing the issue.

**Comment by sambacha** [comment]
This issue still exists

**Comment by robertgendler** [comment]
@sambacha what branch are you working off of? Because I'm not seeing this happen when using the most current

**Comment by sambacha** [comment]
Sonoma

**Comment by robertgendler** [comment]
Still not seeing it. I've tried re-creating the issue and it's working fine and not duplicating "permitrootlogin no"

You'll need to provide either a copy of the rule file from your set up or screenshot or something?
