### ISSUE TITLE
Consider creating a rule that turns off Xcode Ads for Xcode Cloud

### ISSUE THREAD

**Issue by emkinter** [usnistgov/macos_security#207]
### Problem to solve

When starting Xcode, an [Xcode Ads](https://twitter.com/iKenndac/status/1587867958348599308) can be displayed. This may tempt users to subscribe to a non-sanctioned web offering.

### Intended users

Organizations that control web service access.

### Further details

A user starts Xcode, sees an [Xcode Cloud Ad](https://twitter.com/iKenndac/status/1587867958348599308), clicks on it, and starts using an unsanctioned web service.

### Proposal

Check:
/usr/bin/defaults read com.apple.dt.Xcode XcodeCloudUpsellPromptEnabled

Fix:
/usr/bin/defaults write com.apple.dt.Xcode XcodeCloudUpsellPromptEnabled -bool false

### What does success look like, and how can we measure that?

When XcodeCloudUpsellPromptEnabled is set to false in com.apple.dt.Xcode no [Xcode Ads](https://twitter.com/iKenndac/status/1587867958348599308) are displayed when XCode starts.

### Links/references

[Xcode Cloud](https://developer.apple.com/xcode-cloud/)
[Xcode Ads](https://twitter.com/iKenndac/status/1587867958348599308)
[Accidental Tech Podcast - 511: Moving to Antartica](https://atp.fm/511)

**Comment by robertgendler** [comment]
This was decided to not be added as it is not directly in the OS.
