### ISSUE TITLE
system_settings_time_machine_encrypted_configure.yaml incorrect tag for CIS

### ISSUE THREAD

**Issue by ryan-baier-nih** [usnistgov/macos_security#214]
The system_settings_time_machine_encrypted_configure.yaml has the CIS: Benchmark: 2.3.4.2 (level 2) and the tags: set to cis_lvl2.

This control is a Level 1 control per the CIS_Apple_macOS_13.0_Ventura_Benchmark_v1.0.0.
[2022-12-28_12-49-48.pdf](https://github.com/usnistgov/macos_security/files/10315606/2022-12-28_12-49-48.pdf)

**Comment by golbiga** [comment]
This is fixed. Thanks for catching it.
