### ISSUE TITLE
os_hibernate_mode_enable: Standby setting for Apple silicon is incorrect

### ISSUE THREAD

**Issue by jmahlman** [usnistgov/macos_security#219]
### Summary

The check and fix for Apple silicon devices is incorrectly checking for `standbydelay` instead of `standby`. 
The key `standbydelay` does not work on Apple silicon and instead the delay is simply set with the `standby` key. 

### Operating System version

macOS Monterey and macOS Ventura

### Intel or Apple Silicon

Apple Silicon

### What is the current *bug* behavior?

The current check is looking at the value of `standbydelay` which does not exist on Apple silicon devices.
The current fix is setting `standbydelay` which does not exist on Apple silicon devices.

### What is the expected *correct* behavior?

The check and fix should be checking and setting the `standby` key.

### Possible fixes

Update the fix and check:
```yaml
check: |
  error_count=0
  if /usr/sbin/ioreg -rd1 -c IOPlatformExpertDevice 2>&1 | /usr/bin/grep -q "MacBook"; then
    hibernateMode=$(/usr/bin/pmset -b -g | /usr/bin/grep hibernatemode 2>&1 | /usr/bin/awk '{print $2}')
    if [[ "$(/usr/sbin/sysctl -n machdep.cpu.brand_string)" =~ "Intel" ]]; then
        hibernateStandbyLowValue=$(/usr/bin/pmset -g | /usr/bin/grep standbydelaylow 2>&1 | /usr/bin/awk '{print $2}')
        hibernateStandbyHighValue=$(/usr/bin/pmset -g | /usr/bin/grep standbydelayhigh 2>&1 | /usr/bin/awk '{print $2}')
        hibernateStandbyThreshValue=$(/usr/bin/pmset -g | /usr/bin/grep highstandbythreshold 2>&1 | /usr/bin/awk '{print $2}')
        
        if [[ "$hibernateStandbyLowValue" == "" ]] || [[ "$hibernateStandbyLowValue" -gt 600 ]]; then
            ((error_count++))
        fi
        if [[ "$hibernateStandbyHighValue" == "" ]] || [[ "$hibernateStandbyHighValue" -gt 600 ]]; then
            ((error_count++))
        fi
        if [[ "$hibernateStandbyThreshValue" == "" ]] || [[ "$hibernateStandbyThreshValue" -lt 90 ]]; then
            ((error_count++))
        fi
    fi
    if [[ "$hibernateMode" == "" ]] || [[ "$hibernateMode" != 25 ]]; then
      ((error_count++))
    fi
  fi
  echo "$error_count"
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/bin/pmset -a hibernatemode 25
  if [[ "$(/usr/sbin/sysctl -n machdep.cpu.brand_string)" =~ "Intel" ]]; then
    /usr/bin/pmset -a standbydelayhigh 600
    /usr/bin/pmset -a standbydelaylow 600
    /usr/bin/pmset -a highstandbythreshold 90
  fi
  ----
```

**Comment by jmahlman** [comment]
I have opened an Apple enterprise case to get clarification on what `standby` actually does and expects. It seems that it should be a boolean, but I cannot see any difference on the endpoint with it set or not.

**Comment by jmahlman** [comment]
Setting `hibernatemode` to 25 does work on Apple silicon, so that can remain. I have updated my check/fix in the original post.

**Comment by robertgendler** [comment]
@jmahlman any updates?

**Comment by vaughnhart** [comment]
sudo pmset -a destroyfvkeyonstandby 1
sudo pmset -a hibernatemode 25
sudo pmset -a powernap 0
sudo pmset -a standby 0
sudo pmset -a standbydelay 0
sudo pmset -a autopoweroff 0

**Comment by jmahlman** [comment]
Fixes pushed to OS branches.
