### ISSUE TITLE
Include check that FileVault cannot be disabled in system_settings_filevault_enforce or create new rule to check

### ISSUE THREAD

**Issue by moose-juice** [usnistgov/macos_security#220]
### Problem to solve

Include a check that FileVault cannot be disabled. CIS macOS 13 Benchmark v1.0.0 2.6.5 Ensure FileVault is Enabled requires that FileVault is enabled and cannot be disabled. Its check and remediation include confirming FileVault cannot be disabled.

### Intended users

macOS administrators hardening computers to the CIS macOS 13.0 Ventura Benchmark v1.0.0.

### Further details

Administrators and organizations who wish to audit whether FileVault can be disabled will benefit from having this check included in the mSCP.

### Proposal

Add the following check to the system_settings_filevault_enforce rule, or create a new rule that includes the following check.

Map whichever rule that includes this check back to CIS macOS 13.0 Ventura Benchmark v1.0.0 Level 1 2.6.5 Ensure FileVault is Enabled.

`
$ /usr/bin/sudo /usr/bin/osascript -l JavaScript << EOS $.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\ .objectForKey('dontAllowFDEDisable').js EOS
--
true
`

### Documentation
CIS macOS 13.0 Ventura Benchmark v1.0.0 2.6.5 Ensure FileVault is Enabled

### Testing

Risk of including an automated script check that will break the generated compliance script. Risk of including an automated script check that produces false positives or false negatives.

### What does success look like, and how can we measure that?

Success is defined by the inclusion of an automated check/audit process to ensure FileVault cannot be disabled.

### Links / references

CIS macOS 13.0 Ventura Benchmark v1.0.0 2.6.5 Ensure FileVault is Enabled

**Comment by jmahlman** [comment]
Attaching link: https://workbench.cisecurity.org/sections/1447537/recommendations/2326211

**Comment by robertgendler** [comment]
Please check to make sure this works.

We'll migrate it to Big Sur and Monterey if all is good.
