### ISSUE TITLE
Create a script who doesn't need answer to fix non compliant settings

### ISSUE THREAD

**Issue by louisdchrf** [usnistgov/macos_security#229]
### Problem to solve

The compliance script need a human to launch the fix of non compliant settings 

### Intended users

Mac admins using MacDeployServer to deploy Macs. Script can be run during the deployment but automatically. If a script need a answer, deployment is crashing

### Further details

In case where people doesn't use MDM or can sign a configuration profile

### Proposal

Add a argument for launching the script, like 
_sudo ./build/800-53r5_low/800-53r5_low_compliance.sh -apply-compliant_

**Comment by robertgendler** [comment]
`sudo ./build/800-53r5_low/800-53r5_low_compliance.sh --fix` is what you're looking for.

**Comment by golbiga** [comment]
Actually you might want to use the `--cfc` flag. This will do a check, fix, check.

**Comment by louisdchrf** [comment]
Nice argument, I didn't see this on the wiki
