### ISSUE TITLE
Asciidoctor-pdf 2.3.6 [undefined method `absolute_path?' for File:Class] error 

### ISSUE THREAD

**Issue by golbiga** [usnistgov/macos_security#250]
Looks like we have a compatibility issue with asciidoctor-pdf 2.3.6. If you're using an existing repo which was built pre 2.3.6 you wont see this issue but newer builds will. 

```
Generating PDF file from AsciiDoc...
undefined method `absolute_path?' for File:Class
Did you mean?  absolute_path
  Use --trace to show backtrace
```

Hardcoding the asciidoctor-pdf version resolves the issue:
`gem 'asciidoctor-pdf', '~> 2.3', '< 2.3.6'`. 

```
Fetching asciidoctor-pdf 2.3.5
Installing asciidoctor-pdf 2.3.5
Using bundler 1.17.2
Fetching rouge 3.30.0
Installing rouge 3.30.0
Bundle complete! 3 Gemfile dependencies, 24 gems now installed.
Bundled gems are installed into `../mscp_gems`
Generating HTML file from AsciiDoc...
Generating PDF file from AsciiDoc...
```

Looking into a more permanent fix, if none can be found, will update the Gemfile in the project.

**Comment by robertgendler** [comment]
This was merged into main. closing the issue.
