### ISSUE TITLE
Add a default value / Arg to generate_script

### ISSUE THREAD

**Issue by PazDak** [usnistgov/macos_security#26]
### Problem to solve

I would like to make this easier to deploy and make it transparent to a user, but maintain the choice of an admin to choose whether to deploy with or without human interaction. 

### Further details
def generate_script(baseline_name, build_path, baseline_yaml) is the base of the culprit. Give this the ability to bypass by giving it known commands.

**Comment by golbiga** [comment]
@PazDak we're almost done with this, check out [https://github.com/usnistgov/macos_security/tree/script_edit](url). It will generate the same compliance script, but you will be able to use a `--check` or `--fix` to run without interaction.

**Comment by golbiga** [comment]
@PazDak This was added to the project. Thanks for the feedback.
