### ISSUE TITLE
Ventura firewall mobileconfig fails to install

### ISSUE THREAD

**Issue by bernstei** [usnistgov/macos_security#262]
The `com.apple.security.firewall.mobileconfig` generated by the `dev_ventura_stig` branch cannot be installed on Ventura 13.4.  It fails with the message
```
The payload "alacarte.macos.stig....." is missing the required key "EnableFirewall".
```
It appears to set `EnableStealthMode`, but maybe anything having to do with the firewall also requires the `EnableFirewall` key as well now?  I'm not sure what value you'd want to default to, though, since presumably some people might want the Apple firewall while others might want some third party firewall.

I've attached the file (renamed to .txt)

[com.apple.security.firewall.mobileconfig.txt](https://github.com/usnistgov/macos_security/files/11560361/com.apple.security.firewall.mobileconfig.txt)

**Comment by robertgendler** [comment]
Good find.  I guess we have to add the key to enable the firewall to this control. 

Did we miss labeling the enable firewall with a stig label maybe?

**Comment by robertgendler** [comment]
We missed the stig controls on `system_settings_firewall_enable`

But I think it would make sense for us to add the enable firewall stuff to stealth mode as well since it won't work without it.

**Comment by robertgendler** [comment]
This is in `dev_ventura_stig`

**Comment by robertgendler** [comment]
This was merged into main. closing the issue.
