### ISSUE TITLE
firmware password requirement not applicable to Apple silicon according to STIG

### ISSUE THREAD

**Issue by bernstei** [usnistgov/macos_security#265]
Is there any way to automatically handle the fact that the firmware password does not exist for Apple silicon, and the STIG (not sure about other security guidelines), at least as of macOS 12, says that rule is not applicable?

https://github.com/usnistgov/macos_security/blob/2b025e09a2e2458602fdee001bc9122decef4a0c/rules/os/os_firmware_password_require.yaml#L1

**Comment by robertgendler** [comment]
https://github.com/usnistgov/macos_security/blob/10705d95975fedf195d73ca1f0200ecc1b5c6158/rules/os/os_firmware_password_require.yaml#L49

Somehow it got dumped along the way. Here it is on main with `i386`

**Comment by robertgendler** [comment]
Also it appears to be on the `dev_ventura_stig` branch. I'm going to close this out. But I'll make sure it shows up when we merge it all together.

**Comment by robertgendler** [comment]
OH! I just realized you're on the `Catalina` branch.

2 things, Catalina doesn't support Apple Silicon devices. And Catalina is EOL so no updates will be made to it.

**Comment by bernstei** [comment]
Hmm - the `i386` tag is there on Big Sur and Monterey, but I'm sure I've gotten this showing up as a rule failure on M1 macs, because I had to track it down and disable it.  Let me see what's going on.

**Comment by bernstei** [comment]
It's working now - weird.
