### ISSUE TITLE
Remediations on audit_control cause chaos if file is missing

### ISSUE THREAD

**Issue by brodjieski** [usnistgov/macos_security#269]
If /etc/security/audit_control is missing, the remediation script causes issues with the filesystem as it attempts to modify attributes on system folders.

Affects the following rules:
audit_acls_files_configure.yaml
audit_acls_folders_configure.yaml
audit_files_group_configure.yaml
audit_files_mode_configure.yaml
audit_files_owner_configure.yaml
audit_folder_group_configure.yaml
audit_folder_owner_configure.yaml
audit_folders_mode_configure.yaml

**Comment by robertgendler** [comment]
this was merged into main. closing the issue.
