### ISSUE TITLE
CIS Manual Recommendations not generating properly

### ISSUE THREAD

**Issue by Tribruin** [usnistgov/macos_security#282]
### Summary

CIS Manual Recommendations is not properly printing the recommedations for the Applications sections. 

### Steps to reproduce

Generate Guidance for with the CIS Manual Recommendations selected. 

### What is the current *bug* behavior?

The recommendations are blank in the Applications section

### What is the expected *correct* behavior?

Three rules should be listed under recommendations

### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)
https://github.com/usnistgov/macos_security/blob/ventura/rules/supplemental/supplemental_cis_manual.yaml

Line 55 should be `|Recommendations`

**Comment by jmahlman** [comment]
@Tribruin Check this, should be good now.
