### ISSUE TITLE
submit profiles by CIS section vs functionality section

### ISSUE THREAD

**Issue by mattdjerome** [usnistgov/macos_security#283]
### Problem to solve

Currently, the profiles are exported by mac functionality area (i.e. airplay, mcx, filevaule, etc.). It would be great to (at least have the option) export by CIS section

### Intended users

System Admins

### Proposal

Provide an option of exporting by functionality area or CIS section

### What does success look like, and how can we measure that?

An option to export by CIS Sections vs the current method.

**Comment by robertgendler** [comment]
There is no plan to create functionality to export by CIS section.  

CIS controls move from section and grouping and numbering too much. 

Export of profiles are based on their preference domain.
