### ISSUE TITLE
Monterey 800-171 .GlobalPreferences settings mobile config not importing into JAMF

### ISSUE THREAD

**Issue by AlfredAleman** [usnistgov/macos_security#289]
### Summary

Once the project is run the mobile config for .GlobalPreferences settings will not import into JAMF and Apple Configurator. Both show up blank with no configurations within it. All settings are blank.

### Steps to reproduce

Create a baseline using MsCP for 800-171
Open JSS and go to config profiles click new button and import the mobile config from your path.
Look at newly created Config Profile and all settings within it are blank and not configured

Navigate to the file and open with Apple Configurator 2 and inspect. Same behavior all settings are blank and not configured

I have created with Jamf Compliance editor and mscp command line and same results

### Operating System version

Monterey all sub versions
### Intel or Apple Silicon

both Intel based process and Apple Silicon Mac

### What is the current *bug* behavior?

imports blank config profile into jamf pro

### What is the expected *correct* behavior?

the import would create a config profile with settings to control auto reboot after 24 hour period

### Relevant logs and/or screenshots

screen shots of the blank profiles and how I created the profile with the plist which does work

### Output of checks

None

### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)
![Screenshot 2023-08-16 at 2 23 46 PM](https://github.com/usnistgov/macos_security/assets/116595861/1615559f-c142-4f5b-b241-10aa96e2f93a)
![Screenshot 2023-08-16 at 2 24 10 PM](https://github.com/usnistgov/macos_security/assets/116595861/c1511b3e-a39e-4722-ba87-14fd10793617)
![Screenshot 2023-08-16 at 2 24 51 PM](https://github.com/usnistgov/macos_security/assets/116595861/73163631-f916-49c8-a42c-cc7ce82c183b)
![Screenshot 2023-08-16 at 2 24 59 PM](https://github.com/usnistgov/macos_security/assets/116595861/f7d5dffa-ba2a-4d1d-9db6-7a62662e5a2b)
![Screenshot 2023-08-16 at 2 25 56 PM](https://github.com/usnistgov/macos_security/assets/116595861/d1dfdcab-05a7-4e02-a217-3910664c4576)

**Comment by golbiga** [comment]
@AlfredAleman I was just able to import using Jamf Compliance Editor. You are correct that uploading the `com.apple.GlobalPreferences.mobileconfig` as is will not work within Jamf Pro, but it is a valid profile. If you open the profile with Low Profile.app it shows as valid, see image below. 

![Screenshot 2023-08-16 at 3 40 59 PM](https://github.com/usnistgov/macos_security/assets/786537/55dbc4ea-aac4-48bf-a17f-3c5377167a64)

Jamf Compliance Editor uploads it as a custom profile, as we identified the same issue originally. 

<img width="1226" alt="Screenshot 2023-08-16 at 3 46 18 PM" src="https://github.com/usnistgov/macos_security/assets/786537/26112a33-18b3-4e57-985b-bea16aec7b3f">

Hope this helps.

**Comment by robertgendler** [comment]
Closing this issue. There isn't much that we can do about this. It's more a Jamf Pro thing.
