### ISSUE TITLE
icloud_appleid_system_settings_disable (dev_sonoma) refers to deprecated domain

### ISSUE THREAD

**Issue by cipineda** [usnistgov/macos_security#298]
### Summary
`icloud_appleid_system_settings_disable' looks for the `com.apple.systempreferences` domain which is deprecated.
Can it be possible to use the `com.apple.applicationaccess` domain  with the `allowAccountModification` key instead?

### Steps to reproduce
Using `icloud_appleid_system_settings_disable' fails in the scan as I do not use this profile/key on Sonoma systems.

### Operating System version
Sonoma 14.0 Beta 7 (23A5337a)

### Intel or Apple Silicon
both

### What is the current *bug* behavior?

Not really a bug but rather a questioning as to why still using the old method.

### What is the expected *correct* behavior?

use the `com.apple.applicationaccess` domain  with the `allowAccountModification` key

### Relevant logs and/or screenshots

![image](https://github.com/usnistgov/macos_security/assets/62953370/35a3551a-b1fc-4a17-91b1-706041f3b116)

### Possible fixes
use the `com.apple.applicationaccess` domain  with the `allowAccountModification` key as noted on the screenshot.

**Comment by robertgendler** [comment]
Well that's interesting. I didn't realize `allowAccountModification` controlled the AppleID pane. When I read it, I assumed it had to do with the user account.

**Comment by cipineda** [comment]
Yeah, the document is misleading on the new method.
The old one, even though it is deprecated, somehow still works, but I'm trying to stay away, were I can from it.

**Comment by robertgendler** [comment]
I'm not a fan though of how it controls the Apple ID system setting pane. It doesn't gray out anything you just can't click or type anywhere. It's kind of misleading.

**Comment by cipineda** [comment]
It does for me, check the image...
it is visible but all grayed out (can't edit at all).
![image](https://github.com/usnistgov/macos_security/assets/62953370/a509565f-0ea4-41a9-96a9-0d1d8804e74a)

**Comment by robertgendler** [comment]
So that's after you're signed in. Most places who are blocking the system settings pane want to block signing in. 

* Unblock yourself.
* Sign out
* block yourself again

You'll see what I mean.

**Comment by cipineda** [comment]
I unlocked it, signed out and locked again, and the pane is visible but can't click on anything.
It is misleading though, as it should not show anything but "Apple ID" settings are not available. These settings are controlled by a profile." but it does not, you can see but not click.

![image](https://github.com/usnistgov/macos_security/assets/62953370/f3e44be5-ea1a-4ecf-8fd1-37f3a13289fb)

**Comment by robertgendler** [comment]
Ya. So that's why I'm not a fan of it vs blocking the whole pane. Sure it's deprecated but so is auditd and other things.

**Comment by robertgendler** [comment]
This actually solves an older even bigger problem. This also restricts adding Internet Accounts.

**Comment by robertgendler** [comment]
Closing this issue as we now have included the rule `os_account_modification_disable`
