### ISSUE TITLE
Suppress Script Output Option

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#301]
### Discussed in https://github.com/usnistgov/macos_security/discussions/300

<div type='discussions-op-text'>

<sup>Originally posted by **btyl** September 12, 2023</sup>
An option to be able to suppress script output so that it is not captured in Jamf policy logs.  We have a very large Mac population and the output from the script that gets captured in the policy logs is greatly increasing the size of the policy logs table in the database.  Even better would be just to output any failed controls so those can be captured in the policy logs.</div>

**Comment by jmahlman** [comment]
Works except that you will get a false positive with `audit_flags_fm_failed_configure` since you are just filtering for `*"failed"* `. 

Looking at how to fix that...

**Comment by jmahlman** [comment]
Adding the :space: to the check worked for silent for me :)
