### ISSUE TITLE
iCloud privacy relay disable not working 

### ISSUE THREAD

**Issue by mani2care** [usnistgov/macos_security#317]
Deployed the configuration profile using security base line “cloud privacy relay disable “ it’s just grad-out not disabling 
Tried with Monterey and Ventura same results.

**Comment by jmahlman** [comment]
That's what the control does. Unfortunately, Apple does not give a programmatic method for disabling it on an endpoint. The suggestion is to block it at the network level.

**Comment by mani2care** [comment]
Applying the profile and Icloud account login in by default it’s enabled then what is the use of grad out

**Comment by vaughnhart** [comment]
I'm not sure this will help but check the end of this conversation. There is a lsof list of files/services that were open when PrivateRelay was enabled. 

https://github.com/usnistgov/macos_security/discussions/288#discussioncomment-7034369

**Comment by vaughnhart** [comment]
I'm not sure this will help but check the end of this conversation. There is a lsof list of files/services that were open when PrivateRelay was enabled. 

https://github.com/usnistgov/macos_security/discussions/288#discussioncomment-7034369

**Comment by robertgendler** [comment]
@mani2care open a feedback with Apple. Unfortunately, almost none of the iCloud controls will turn the feature off. It just disables the ability to toggle them. So if someone has turn it on, you'll have to get the person to turn it off then re-lock the feature.
