### ISSUE TITLE
Add requirement to review exemptions to smart card login.

### ISSUE THREAD

**Issue by akegerreis** [usnistgov/macos_security#337]
If a site is using smart card login but is also allowing unmapped users, the exemption list should be documented with the ISSM.

**Comment by robertgendler** [comment]
@akegerreis do you have a suggestion on how this should appear in the project?

A note in supplemental where unmapped users is talked about?
A separate rule?

**Comment by akegerreis** [comment]
@robertgendler we have this slated to go into the supplemental for our April release of the STIG.
