### ISSUE TITLE
os_mail_app_disable results in annoying popups after every login

### ISSUE THREAD

**Issue by nihil-admirari** [usnistgov/macos_security#340]
After `os_mail_app_disable` is applied, the following popup is shown shortly after every login:
![mail](https://github.com/usnistgov/macos_security/assets/50202386/12e61161-b7bf-4fee-91c3-15c234449bc6)

**Comment by robertgendler** [comment]
This control from Apple is deprecated and not really recommended to use.  It's included for those orgs that really really want to use it. 

Also this is an Apple issue, when blocking Apple mail you get that pop up.
