### ISSUE TITLE
SIP protected services

### ISSUE THREAD

**Issue by nihil-admirari** [usnistgov/macos_security#345]
[os_anti_virus_installed](https://github.com/usnistgov/macos_security/blob/sonoma/rules/os/os_anti_virus_installed.yaml) and [os_time_server_enabled](https://github.com/usnistgov/macos_security/blob/sonoma/rules/os/os_time_server_enabled.yaml) are trying to configure services that are SIP protected, i.e. these services cannot be loaded or unloaded, and their disablement status is always ignored.

Since SIP is enforced by [os_sip_enable](https://github.com/usnistgov/macos_security/blob/sonoma/rules/os/os_sip_enable.yaml), it may be better to check that these services were not added to `/System/Library/Sandbox/com.apple.xpc.launchd.rootless.plist`, rather than trying to `launchctl load -w` them (which errors anyway)?

**Comment by robertgendler** [comment]
We're going to make some changes to the rules that check SIP protected services. It's important to check the status since someone could disable SIP, disable the service, enable SIP.

**Comment by robertgendler** [comment]
@nihil-admirari check out `dev_sonoma_issue345`
