### ISSUE TITLE
system_settings_remote_management_disable avoid undocumented mdmclient

### ISSUE THREAD

**Issue by nihil-admirari** [usnistgov/macos_security#347]
[system_settings_remote_management_disable](https://github.com/usnistgov/macos_security/blob/main/rules/system_settings/system_settings_remote_management_disable.yaml) check uses `mdmclient`, whose man page states:

> WARNING: All command arguments are private. The arguments and output can and will change without notice. Do not rely on any output this command may produce.

CIS “2.3.3.6 Ensure Remote Management Is Disabled” simply does a `pgrep`:
```sh
! /usr/bin/pgrep -q ARDAgent && :
echo $?
```

May be it makes sense to switch away from `mdmclient`, considering that CIS have already done so?

**Comment by robertgendler** [comment]
We use a lot of undocumented things within the project.  mdmclient commands seem safe enough.

**Comment by robertgendler** [comment]
Reviewing this again. If `mdmclient` does change and ends up being not the best method to check when an OS update or upgrade is released, we will update our checks appropriately.
