### ISSUE TITLE
os_world_writable_system_folder_configure new restricted folder 

### ISSUE THREAD

**Issue by golbiga** [usnistgov/macos_security#355]
`/System/Volumes/Data/System/Library/AssetsV2/locks/` needs to be added to ignore list for the check:

`sudo /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -vE "downloadDir|locks" | /usr/bin/wc -l | /usr/bin/xargs`

**Comment by golbiga** [comment]
Fixed.

**Comment by ww-adamb** [comment]
@golbiga Would it be better to exclude SIP protected files by filter on `restricted` instead of maintaining an ignore list?

```
/usr/bin/find /System/Volumes/Data/System -type d -perm -2 -exec ls -lOd {} ';' | /usr/bin/grep -v "restricted" | /usr/bin/wc -l | /usr/bin/xargs
```
