### ISSUE TITLE
SyntaxWarning for python string \| with sufficiently new python version

### ISSUE THREAD

**Issue by bernstei** [usnistgov/macos_security#361]
Running `generate_guidance.py` under python 3.12 leads to many `SyntaxWarning`, e.g.
```
./scripts/generate_guidance.py:2112: SyntaxWarning: invalid escape sequence '\|'
  rule_id=rule_yaml['id'].replace('|', '\|'),
```

It appears that most recent python syntax interprets `'\|'` as an attempt to escape the `|`. I think it can be replaced with `r'\|'` or `'\\|'`, but a, I'm not 100% sure this is right, and b, I'm not sure what python versions this project intends to support and whether they support this new raw string syntax.

**Comment by robertgendler** [comment]
Merged into the OS branches.
