### ISSUE TITLE
unable to generate tailored baseline

### ISSUE THREAD

**Issue by ericbeme** [usnistgov/macos_security#366]
### Summary

unable to generate tailored baseline based off of stif

### Steps to reproduce

try to tailor a baseline

### Operating System version

Sonoma 14.3.1. (yes i am working out of the right branch)...

### Intel or Apple Silicon
Apple Silicon Mac

### What is the current *bug* behavior?
asks normal questions until os_install_log_retention_configure" in your benchmark? [Y/n/all/?]: y

then stops and outputs the following:

ODV value: Number of days.
Traceback (most recent call last):
  File "/Users/mediaadmin/macos_security/./scripts/generate_baseline.py", line 562, in <module>
    main()
  File "/Users/mediaadmin/macos_security/./scripts/generate_baseline.py", line 551, in main
    odv_baseline_rules = odv_query(found_rules, benchmark)
  File "/Users/mediaadmin/macos_security/./scripts/generate_baseline.py", line 442, in odv_query
    if isinstance(rule.rule_odv[benchmark], int):
KeyError: 'stig'

### What is the expected *correct* behavior?

continue to ask ?'s to tailor baseline

### Relevant logs and/or screenshots
<img width="912" alt="Screenshot 2024-02-26 at 3 14 09 PM" src="https://github.com/usnistgov/macos_security/assets/161378371/5e274f99-a550-473d-9256-6c39488bdb71">

**Comment by robertgendler** [comment]
Thanks for finding this! @brodjieski just fixed it and PR #367 should have fixed it and some other DISA STIG related issues.
