### ISSUE TITLE
Option to sign generated profiles please!

### ISSUE THREAD

**Issue by cistone** [usnistgov/macos_security#37]
Your tools generate unsigned profiles. Consider adding a flag that accepts the name of a signing identity in my keychain which will then be used to sign the profiles.

I expect that anyone who manually generates baselines would like to have this feature.

**Comment by psuedoexpert** [comment]
An option to accept the name or hash of the signing identity would be ideal.

**Comment by golbiga** [comment]
This has now been added to the big_sur and catalina branches. It will be merged into main in the next release.

**Comment by golbiga** [comment]
Closing issue.
