### ISSUE TITLE
Add --no-rcs to compliance script

### ISSUE THREAD

**Issue by golbiga** [usnistgov/macos_security#377]
https://scriptingosx.com/2024/03/zsh-scripts-and-root-escalations/

We should add `--no-rcs` to the #!/bin/zsh shebang

**Comment by nihil-admirari** [comment]
Maybe it would've been better to make sudo sanitise `$HOME`, which is what every Linux distro out there is doing?

Proposed fix: comment the following from `/etc/sudoers` (other environment variable may be worth sanitising too)
```
Defaults  env_keep += "HOME MAIL"
```
