### ISSUE TITLE
profile_generator.py - All baselines use the same 'mobileconfigs' directory

### ISSUE THREAD

**Issue by peterlewis** [usnistgov/macos_security#4]
### Summary

When running `profile_generator.py`, no matter which baseline you are targeting, the outputted `.mobileconfig` files are put into a folder named `mobileconfigs`. This means that, when running the script against multiple baselines, the `.mobileconfig` files are combined into a single directory.

When running 
### Steps to reproduce

1. Run `python3 profile_generator.py ../baselines/high.yaml`
2. Run `python3 profile_generator.py ../baselines/low.yaml`

### Operating System version

10.15.5 (19F101)

### What is the current *bug* behavior?

The `mobileconfigs` directory contains `.mobileconfig` files from both of steps 1 and 2

### What is the expected *correct* behavior?

In line with the behaviour of the other scripts, I believe that output directory should contain the name of the targeted baseline, e.g.:

- high_mobileconfigs
- moderate_mobileconfigs
- low_mobileconfigs

### Possible fixes

I think that something along the lines of the following, should fix:

```
# Output folder
mobileconfig_output_path = os.path.join(parent_dir, 'build', ''+profile_name+'_mobileconfigs')
```

I would open a PR myself, but not hugely Python-y and so wouldn't wish to define/duplicate `profile_name` in the wrong place/way.

Many thanks!

Peter

**Comment by golbiga** [comment]
This has been fixed in the 0.9_prerelease branch, it will be included in the release.

Thanks for reporting it.

**Comment by peterlewis** [comment]
That's great. Thanks, @golbiga, for sorting that out so quickly!

**Comment by golbiga** [comment]
@peterlewis, one thing to note. The output will still be in the mobileconfigs folder. There will just be an additional folder within, based on the selected baseline.

<img width="485" alt="Screen Shot 2020-06-15 at 9 52 10 AM" src="https://user-images.githubusercontent.com/786537/84765535-5d675200-af9d-11ea-8ac0-ea5f470a7b1c.png">

**Comment by peterlewis** [comment]
Sounds/looks good, to me! So long as I'm not unintentionally overwriting .mobileconfig sets, then I'm happy! :)

**Comment by golbiga** [comment]
The fix is in master, please test. Closing issue.
