### ISSUE TITLE
audit_events Sandbox violations

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#41]
Audit is overly busy and talkative 

Editing the audit_event file and changing
`43127:AUE_MAC_SYSCALL:mac_syscall(2):ad`
to
`43127:AUE_MAC_SYSCALL:mac_syscall(2):zz`
Will stop sandbox violations from being in the audit logs but make them still auditable if desired using the zz flag.

Possibly adding an audit supplemental or rule.

**Comment by robertgendler** [comment]
Added a note in audit_flags_ad_configure with commit dc3e5e1e278b95b5c6dc4cf2a69265f1af07ff6e

**Comment by golbiga** [comment]
merged with `main`
