### ISSUE TITLE
system_settings_siri_listen_disable result check incorrect

### ISSUE THREAD

**Issue by jmahlman** [usnistgov/macos_security#411]
### Summary

The control `system_settings_siri_listen_disable` is looking for the result of `0` when it should be expecting `false`.

### Steps to reproduce

1. Create a profile with the `system_settings_siri_listen_disable` settings and deploy. 
2. Run the check command manually
3. Observe output

### Operating System version

14.6.1

### Intel or Apple Silicon

N/A

### What is the current *bug* behavior?

The check will result in a finding as the check is expecting a "1"

### What is the expected *correct* behavior?

No finding, check for "false"

### Relevant logs and/or screenshots

Included.

### Output of checks

![Screenshot 2024-08-20 at 10 35 19 AM](https://github.com/user-attachments/assets/66b40aef-bfdc-4e24-9c32-80c6290997df)

### Possible fixes

Change:
```yaml
#remove: 
result:
  integer: 1

#replace:
result:
  string: 'false'
```

**Comment by brodjieski** [comment]
There may be an additional issue going on here.  When running generate_guidance, these pop up when building profiles... 
```
There are errors in the following files, please correct the .yaml file(s)!
../rules/system_settings/system_settings_siri_listen_disable.yaml
../rules/system_settings/system_settings_siri_listen_disable.yaml
```

This is because the rule yaml file has `com.apple.siri` as the payload, but we have `com.apple.Siri` as a supported payload. Need to verify the correct syntax.

**Comment by chadmorales** [comment]
<img width="348" alt="Screenshot 2024-08-30 at 2 52 53 PM" src="https://github.com/user-attachments/assets/bf51589b-a4da-44d2-9b59-e48d9f14469e">
Does not look like the siri profile is being created. Also could not find the VoiceTriggerUserEnabled being set anywhere else in the generated files

**Comment by jmahlman** [comment]
> There may be an additional issue going on here. When running generate_guidance, these pop up when building profiles...
> 
> ```
> There are errors in the following files, please correct the .yaml file(s)!
> ../rules/system_settings/system_settings_siri_listen_disable.yaml
> ../rules/system_settings/system_settings_siri_listen_disable.yaml
> ```
> 
> This is because the rule yaml file has `com.apple.siri` as the payload, but we have `com.apple.Siri` as a supported payload. Need to verify the correct syntax.

Ah yeah, I see in the rule it's using `com.apple.siri`. I'm almost 100% certain it should be capital S.
