### ISSUE TITLE
system_settings_loginwindow_loginwindowtext_enable appear in the configuration profile when not selected 

### ISSUE THREAD

**Issue by mani2care** [usnistgov/macos_security#416]
"In every new project creation, I have excluded or unselected 'system_settings_loginwindow_loginwindowtext_enable' in security compliance, and then loaded it into Jamf. Later, the profiles and scripts appear in the configuration profile and extension attribute."

**Comment by golbiga** [comment]
This is possibly a JCE issue and not a mscp issue. Closing the ticket.
