### ISSUE TITLE
custom reference data should be displayed in generated documents and spreadsheet 

### ISSUE THREAD

**Issue by thebestoneever** [usnistgov/macos_security#42]
Allow customized reference data to be displayed in generated documentation and spreadsheets.

This allows users of the guidance to reference categories that identify elements of data specific to their usage.

This is for users that create custom content.

**Comment by golbiga** [comment]
This will be in the next release. You can add any custom references to the custom reference section and it will appear in documentation and the spreadsheet.

```
custom:
    Custom:
      - Custom1
      - Custom2
    URL:
      - https://www.apple.com
      - https://www.google.com
    Remediation Tool:
      - Jamf Pro
```
