### ISSUE TITLE
cross reference for how rules are implemented in a tool

### ISSUE THREAD

**Issue by thebestoneever** [usnistgov/macos_security#43]
Allow a way for tool builders to map the implementation of rules to features in their tools. This mapping should be able to be created in an independent file and then mapped into the references section via a script.

**Comment by golbiga** [comment]
This will be in the next release. You can add Remediation Tool to the custom reference section and it will appear in documentation and the spreadsheet.

  ```
custom:
    Remediation Tool:
      - Jamf Pro
```

**Comment by golbiga** [comment]
Closing issue as workflow has been added to both `big_sur` and   `catalina` branches
