### ISSUE TITLE
fix for os_ssh_server_alive_interval_configure.yaml is not successful

### ISSUE THREAD

**Issue by jeolsen** [usnistgov/macos_security#446]
### Summary

When running the fix code supplied by STIG and included in the yaml, an error is generated.  This does not seem to be an issue from the mSCP side, but from the code STIG provides.

### Steps to reproduce

run fix text script

### Operating System version

macOS 15.2

### Intel or Apple Silicon

Apple Silicon

### What is the current *bug* behavior?

fix is not applied

### What is the expected *correct* behavior?

ServerAliveInterval should be set to 900 (or value determined by organization)

### Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output, logs, and code as it's tough to read otherwise.)

### Output of checks

line 15: ${(f)configfiles}: bad substitution

### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by jeolsen** [comment]
@robertgendler I'm copying into an empty script.sh file for testing, adding #!/bin/sh to the top, and then running sudo sh ~/script.sh to execute it. 
<img width="697" alt="Screenshot 2024-11-13 at 10 25 20 AM" src="https://github.com/user-attachments/assets/9db9016e-e0ce-46f7-81f2-476298ff9daf">
<img width="912" alt="Screenshot 2024-11-13 at 10 25 00 AM" src="https://github.com/user-attachments/assets/a18df8fc-85c9-45e1-826b-ee9501c6b5e6">

**Comment by robertgendler** [comment]
can the shell at the top to `/bin/zsh` it's not a bash shell script...it's a zsh script.

**Comment by jeolsen** [comment]
That looks like the issue.  Running with zsh worked.  Thank you
