### ISSUE TITLE
Add Apple Intelligence Controls

### ISSUE THREAD

**Issue by emkinter** [usnistgov/macos_security#448]
### Problem to solve

Identify the appropriate guidance and, if necessary, establish rules for controls to either restrict or permit the utilization of Apple Intelligence Currently, there are some recognized features that fall under this category:

* allowWritingTools
* allowMailSummary
* allowGenmoji
* allowImagePlayground
* allowImageWand

**Features Introduced in macOS Sequoia 15.2 and Subsequent iOS Versions 18.2:**
* allowExternalIntelligenceIntegrations
* allowExternalIntelligenceIntegrationsSignIn

### Intended users

User of mSCP

### Further details

Given the potential risk of data leakage associated with Apple Intelligence Features, it is imperative to establish the appropriate controls for their management.

### Proposal

After determining the appropriate guidance for Apple Intelligence Features create rules to implement that guidance.

### Documentation

* [Apple Device Management GitHub - seed_iOS-18.2_macOS-15.2](https://github.com/apple/device-management/tree/seed_iOS-18.2_macOS-15.2)
* [Apple Device Management GitHub](https://github.com/apple/device-management/)
* [Raising Your IQ on Apple Intelligence](https://boberito.medium.com/raising-your-iq-on-apple-intelligence-380933894340)

### Testing

N/A

### What does success look like, and how can we measure that?

The appropriate guidance is developed for Apple Intelligence Features, and corresponding rules are either created or not.

### Links / references

* [Apple Device Management GitHub - seed_iOS-18.2_macOS-15.2](https://github.com/apple/device-management/tree/seed_iOS-18.2_macOS-15.2)
* [Apple Device Management GitHub](https://github.com/apple/device-management/)
* [Apple Intelligence](https://www.apple.com/apple-intelligence/)
* [How to get Apple Intelligence](https://support.apple.com/en-us/121115)
* [Raising Your IQ on Apple Intelligence](https://boberito.medium.com/raising-your-iq-on-apple-intelligence-380933894340)

**Comment by jmahlman** [comment]
These are not released to the public at this time, and no benchmarks/baselines have these right now. However, once the versions go to RC, it may be safe to assume that they will be added.

**Comment by emkinter** [comment]
> These are not released to the public at this time, and no benchmarks/baselines have these right now. However, once the versions go to RC, it may be safe to assume that they will be added.

I updated the issue.

**Comment by robertgendler** [comment]
Closing cause this is all added and completed
