### ISSUE TITLE
Definition of exemption

### ISSUE THREAD

**Issue by sebastianvoss** [usnistgov/macos_security#56]
I followed the instruction outlined at https://github.com/usnistgov/macos_security/wiki/Compliance-Script:

```
sudo /usr/libexec/PlistBuddy -c "Delete os_firmware_password_require" /Library/Preferences/org.800-53_moderate.audit.plist
sudo /usr/libexec/PlistBuddy -c "Add :os_firmware_password_require:exempt bool true" /Library/Preferences/org.800-53_moderate.audit.plist
sudo /usr/libexec/PlistBuddy -c "Add :os_firmware_password_require:finding bool false" /Library/Preferences/org.800-53_moderate.audit.plist
sudo /usr/libexec/PlistBuddy -c "Add :os_firmware_password_require:exempt_reason string 'Not supported for VM'" /Library/Preferences/org.800-53_moderate.audit.plist
```

But when I run `sudo ./build/800-53_moderate/800-53_moderate_compliance.sh` this rule is still failing:

```
ERROR | SetupTRBSettings | The firmware on this machine is not supported.
ERROR | main | Exiting with error: 5
Thu Mar 11 13:35:07 UTC 2021 os_firmware_password_require failed (Result: 0, Expected: {integer: 1})
```

How can I disable `os_firmware_password_require`?

**Comment by golbiga** [comment]
@sebastianvoss which branch are you working off? The exemption feature has not made it to main yet. Depending on which OS you are looking to run on check either catalina or big_sur.

**Comment by sebastianvoss** [comment]
Thanks for your fast reply! 

I tried with `main` and also with `big_sur_rev1` just now. But it shows the same behaviour. Do I need to use a different branch for MacOS Big Sur?

**Comment by golbiga** [comment]
Yes, do a git checkout of big_sur and the exemption code will be in there. We're hoping to do a new revision for Catalina and Big Sur soon that will have that code in main. Let me know if that works.

**Comment by sebastianvoss** [comment]
It works!

```
Thu Mar 11 14:33:54 UTC 2021 os_firmware_password_require has an exemption (Reason: Not needed for VM)
```

Thanks again for your help and this great project.
