### ISSUE TITLE
os_sshd_key_exchange_algorithm_configure.yaml does not have a fallback to adding the relevant line

### ISSUE THREAD

**Issue by noambernstein** [usnistgov/macos_security#67]
### Summary

os_sshd_key_exchange_algorithm_configure.yaml fails because there is no KexAlgorithms in sshd_config, and unlike the other sshd_config rules it does not fall back to appending such a line 

### Steps to reproduce

run build/PROFILE/PROFILE_compliance.sh, tell it to fix os_sshd_key_exchange_algorithm_configure, then run it again and see that it hasn't actually fixed it because there's no line to change with sed.

### Operating System version

11.3.0

### What is the current *bug* behavior?

When no KexAlgorithms entry is in /etc/ssh/sshd_config is present, a correct one is not added

### What is the expected *correct* behavior?

When no KexAlgorithms entry is in /etc/ssh/sshd_config is present, a correct one *is* added

### Possible fixes

https://github.com/usnistgov/macos_security/blob/ebca0938531b2b3e077966c6f3c083636a91bc2b/rules/os/os_sshd_key_exchange_algorithm_configure.yaml#L20
needs a `grep ...  || echo .... >> ....` type behavior like, e.g. https://github.com/usnistgov/macos_security/blob/ebca0938531b2b3e077966c6f3c083636a91bc2b/rules/os/os_ssh_fips_140_ciphers.yaml#L18

**Comment by golbiga** [comment]
merged with `main`
