### ISSUE TITLE
Rule - os_filevault_user_account - Change needed for Apple silicon

### ISSUE THREAD

**Issue by ericbenfer** [usnistgov/macos_security#76]
### Summary
Rule - os_filevault_user_account.yaml - Create a new user account that will be used to unlock the disk on startup.
Apple Silicon systems do not like: sudo dscl . append /Users/<FileVault_User> AuthenticationAuthority DisabledUser
Once you use DisableUser on M1 that user can no longer unlock FV.

Change the user shell to “/usr/bin/false”
This will work for Intel and Apple silicon.

### Steps to reproduce

(How one can reproduce the issue - this is very important)

### Operating System version

macOS 11.4 (20F71)

### What is the current *bug* behavior?

Once you use DisableUser on M1 that user can no longer unlock FV.

### What is the expected *correct* behavior?

User should be disabled for login, but should still be able to unlock FileVault.

### Possible fixes

Change the user shell to “/usr/bin/false”
This will work for Intel and Apple silicon.

Updated check: `# sudo dscl . -read /Users/<FileVault_User> UserShell | grep "/usr/bin/false"`

Updated Fix: `# sudo dscl . -create /Users/<FileVault_User> UserShell “/usr/bin/false”`

**Comment by golbiga** [comment]
This rule was removed from and replaced with `os_filevault_authorized_users` in `main`.
