### ISSUE TITLE
Add "all_rules" to generate_baseline.py -l

### ISSUE THREAD

**Issue by ericbenfer** [usnistgov/macos_security#77]
### Problem to solve

Please add "all_rules" to the list for `"${ProjectDirectory}/scripts/generate_baseline.py" -l`

This will give you the ability to more easily generate guidance and review all the project rules.

**Comment by golbiga** [comment]
You can already do this with `./scripts/generate_baseline.py -k all`. This will create `build/baselines/all.yaml`. We will update the documentation. Thanks!
