### ISSUE TITLE
audit_control policy cnt vs ahlt

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#78]
audit_failure_halt recommends adding the ahlt to the audit_control policy section which will halt the system if it runs out of space and not able to write the audit logs to disk.

We are not removing cnt which allows things to continuing running even though events are not being audited.

https://www.freebsd.org/cgi/man.cgi?query=audit_control&sektion=5&n=1

We should be checking for cnt and replacing it with ahlt.

**Comment by golbiga** [comment]
New Check: `/usr/bin/awk -F':' '/^policy/ {print $NF}' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec 'ahlt'`

New Fix: `/usr/bin/sed -i.bak 's/^policy.*/policy: ahlt,argv/' /etc/security/audit_control; /usr/sbin/audit -s`
