### ISSUE TITLE
Prevent fixes when not needed

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#80]
In rules that edit text files, adding 

`/usr/bin/grep -qE "(regular expression from the check) file/to/change || (current fix)`

It will prevent the fix from occurring if not needed

for audit_flags_ad_configure for example
`/usr/bin/grep -qE "^flags.*[^-]ad" /etc/security/audit_control || /usr/bin/sed -i.bak '/^flags/ s/$/,ad/' /etc/security/audit_control; /usr/sbin/audit -s`

**Comment by golbiga** [comment]
This has been addressed in `main`, `big_sur`, and `catalina`.
